// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void insuranceQuote0125and3and04500()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("51dvjnjs");
        driver.FindElement(By.Id("city")).SendKeys("ijowvsl");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("512-522-2252");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4500"));
        }
    }
    [Test]
    public void insuranceQuote0225and3and24500()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("51vdbscjabh");
        driver.FindElement(By.Id("city")).SendKeys("bkbk");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("521-525-4545");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4500"));
        }
    }
    [Test]
    public void insuranceQuote0335and10and4NoInsuranceforyou()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("51 sdvbk");
        driver.FindElement(By.Id("city")).SendKeys("jfvsk");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3s4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("512-525-4555");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insuranceQuote04invalidPhoneNumberwith27and3and0PhoneNumbermustfollowthepatterns()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda ");
        driver.FindElement(By.Id("address")).SendKeys("51 sidvbisk");
        driver.FindElement(By.Id("city")).SendKeys("vdn kj");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w3");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("5195252525");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void insuranceQuote05InvalidEmailwith28and3and0Mustbeavalidemailaddress()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("51nsdjvbi");
        driver.FindElement(By.Id("city")).SendKeys("jbk ");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-504-2722");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("jongwick.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void insuranceQuote06InvalidPostalCodewith35and17and1PostalCodemustfollowthepatternA1A1A1()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div > .form-group:nth-child(1)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("51hvbsjh");
        driver.FindElement(By.Id("city")).SendKeys("jvridsb j");
        driver.FindElement(By.Id("postalCode")).SendKeys("n22l3ws");
        driver.FindElement(By.Id("phone")).SendKeys("519-504-5252");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("17");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("addForm")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void insuranceQuote07AgeOmmitedwith5and0Age16isrequired()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("51vndkb");
        driver.FindElement(By.Id("city")).SendKeys("hbjh");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w4");
        driver.FindElement(By.Id("phone")).SendKeys("519-504-2728");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void insuranceQuote08NumberOfAccidentsOmmitedwith37and8Numberofaccidentsisrequired()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("51shvbjha");
        driver.FindElement(By.Id("city")).SendKeys("hbj");
        {
            var dropdown = driver.FindElement(By.Id("province"));
            dropdown.FindElement(By.XPath("//option[. = 'BC']")).Click();
        }
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3wh");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w3");
        driver.FindElement(By.Id("phone")).SendKeys("519-525-4445");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void insuranceQuote09YearsofDrivingExperienceOmmitedwith45and0Yearsofexperienceisrequired()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("NAdoda");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("56");
        driver.FindElement(By.Id("address")).SendKeys(Keys.Enter);
        driver.FindElement(By.Id("address")).SendKeys("56wdjvk");
        driver.FindElement(By.Id("city")).SendKeys("jbkjd");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w3");
        driver.FindElement(By.Id("phone")).SendKeys("519-585");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-585-7848");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void insuranceQuote1025and0and06000()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("513jdnvj");
        driver.FindElement(By.Id("city")).SendKeys("jbfkvb");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3e4");
        driver.FindElement(By.Id("phone")).SendKeys("519-525-4554");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$6000"));
        }
    }
    [Test]
    public void insuranceQuote1140and12and6NoInsuranceforyou()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("5jndvjk");
        driver.FindElement(By.Id("city")).SendKeys("jfdk");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 2w3");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-556-5152");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("40");
        driver.FindElement(By.Id("experience")).SendKeys("12");
        driver.FindElement(By.Id("accidents")).SendKeys("6");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insuranceQuote1235and1and24500()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("54fvniknj");
        driver.FindElement(By.Id("city")).SendKeys("bkhb");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3e4");
        driver.FindElement(By.Id("phone")).SendKeys("512-525-4545");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("1");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4500"));
        }
    }
    [Test]
    public void insuranceQuote1332and2and03285()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("564dnvksj");
        driver.FindElement(By.Id("city")).SendKeys("jfvk");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3e4");
        driver.FindElement(By.Id("phone")).SendKeys("519-566-5464");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("32");
        driver.FindElement(By.Id("experience")).SendKeys("2");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$3285"));
        }
    }
    [Test]
    public void insuranceQuote1431and12and12190()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("54fvnjks");
        driver.FindElement(By.Id("city")).SendKeys("jfkv");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3w4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("519-454-5454");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("31");
        driver.FindElement(By.Id("experience")).SendKeys("12");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2190"));
        }
    }
    [Test]
    public void insuranceQuote1518and1and3NoInsuranceforyou()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(680, 834);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Jaydeep");
        driver.FindElement(By.Id("lastName")).SendKeys("Nadoda");
        driver.FindElement(By.Id("address")).SendKeys("51fjvbsjdh");
        driver.FindElement(By.Id("city")).SendKeys("hbhj");
        driver.FindElement(By.Id("postalCode")).SendKeys("n2l 3e4");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("514-545-525");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("514-545-5255");
        driver.FindElement(By.Id("email")).SendKeys("j");
        driver.FindElement(By.Id("email")).SendKeys(Keys.Down);
        driver.FindElement(By.Id("email")).SendKeys("jaydeepnadoda@gmial.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("18");
        driver.FindElement(By.Id("experience")).SendKeys("11");
        driver.FindElement(By.Id("accidents")).SendKeys("3");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".col-md-4:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).ClickAndHold().Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".col-md-4:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.CssSelector(".col-md-4:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Release().Perform();
        }
        driver.FindElement(By.CssSelector(".form-row:nth-child(4)")).Click();
        {
            var element = driver.FindElement(By.CssSelector(".form-row:nth-child(4)"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
}
